run-name: '[PR #${{github.event.pull_request.number}}] [Marketing Sample] Build frontend and backend containers'


on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the backend
        run: |
          docker build -t support-center-backend -f samples/support-center/src/backend/Dockerfile .
        shell: pwsh

      - name: Build the frontend
        run: |
          cd samples/support-center/src/frontend/
          docker build -t support-center-frontend .
        shell: pwsh