name: Release all nuget packages

on:
   push:
     paths:
     - 'src/**'
 
permissions:
    id-token: write
    contents: read
jobs:
    initialize-context:
      uses: ./.github/workflows/nuget/initialize-context.yml
      secrets: inherit
    build-test-packages:
      uses: ./.github/workflows/nuget/build-test-packages.yml
      needs: [initialize-context]
      secrets: inherit
    publish-core:
      if: github.ref == 'refs/heads/main'  # This job runs only if the push is to the main branch
      needs: [build-test-packages, initialize-context]
      uses: ./.github/workflows/nuget/publish-nuget.yml
      with:
        package-name: Oagents.Core
        version-prefix: 0.0.2
        version-suffix: ${{ needs.initialize-context.outputs.version_suffix }}"
      secrets: inherit
    publish-orleans:
      if: github.ref == 'refs/heads/main'  # This job runs only if the push is to the main branch
      needs: [build-test-packages, initialize-context]
      uses: ./.github/workflows/nuget/publish-nuget.yml
      with:
        package-name: Oagents.Orleans
        version-prefix: 0.0.2
        version-suffix: ${{ needs.initialize-context.outputs.version_suffix }}"
      secrets: inherit