name: '[OAgents nuget] Publish nuget package'

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      version-prefix:
          required: true
          type: string
      version-suffix:
          required: true
          type: string
    secrets:
      NUGET_API_KEY:
        required: true

  # 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish package
      run: |
        cd src/${{ inputs.package-name }}
        dotnet pack -o packages /p:PackageVersion=${{ inputs.version-prefix }}-alpha.${{ inputs.version-suffix }}
        dotnet nuget push $GITHUB_WORKSPACE/src/${{ inputs.package-name }}/packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}  --source https://api.nuget.org/v3/index.json