name: '[Support Center Sample] Build sample application'
run-name: '[PR #${{github.event.pull_request.number}}] [Support Center Sample] Build sample application'

on:
  push:
    branches:
      - main
    paths:
      - samples/support-center/**
      - .github/workflows/support-center-build.yml
      - src/**
  pull_request:
    branches:
      - '**'
    paths:
    - samples/support-center/**
    - .github/workflows/support-center-build.yml
    - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the backend
        run: |
          docker build -t support-center-backend -f samples/support-center/src/backend/Dockerfile .
        shell: pwsh

      - name: Build the frontend
        run: |
          cd samples/support-center/src/frontend/
          docker build -t support-center-frontend .
        shell: pwsh